# needed to securely identify the workflow
name: autofix.ci

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: "pnpm"

      - run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🚨 Install Playwright browsers
        run: pnpm playwright install

      - name: 🔠 Fix lint errors
        run: pnpm lint --fix

      - name: 🧪 Update unit test snapshots
        run: pnpm test:unit -u

      - name: 🏃 Update component test snapshots
        run: pnpm test:nuxt -u

      - name: 🖥️ Update browser test snapshots
        run: pnpm test:e2e --update-snapshots

      - uses: autofix-ci/action@7a166d7532b277f34e16238930461bf77f9d7ed8
