name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🔠 Lint project
        run: pnpm lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🚨 Install Playwright browsers
        run: pnpm playwright install

      - name: 💪 Type check
        run: pnpm test:types

      - name: 🧪 Unit test
        run: pnpm test:unit

      - name: 🏃 Component tests
        run: pnpm test:nuxt

  browser:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.59.1-noble

    steps:
      - uses: actions/checkout@v6
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🖥️ Test project (browser)
        run: pnpm test:e2e
